name: Build Chinese Version

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build APK (汉化版)

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-overwrite-existing: true

      - name: Create Debug Sign File
        run: |
          keytool -genkey -v -keystore keystore.jks -keyalg RSA -keysize 2048 -validity 10000 \
            -alias debug -storepass android -keypass android \
            -dname "CN=FoldDevtools, OU=Debug, O=Local, L=Local, ST=Local, C=CN"
          printf 'storeFile=../keystore.jks\nstorePassword=android\nkeyAlias=debug\nkeyPassword=android\n' > signing.properties

      - name: Build App Debug
        run: bash gradlew assembleDebug

      - name: Find APKs
        run: |
          echo "APK_FILE_DEBUG=$(find app/build/outputs/apk/debug -name '*.apk')" >> $GITHUB_ENV

      - name: Show Artifacts Summary
        run: |
          echo "### 构建成功 :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "|类型|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:--------:|:----------|" >> $GITHUB_STEP_SUMMARY
          debug=($(sha256sum ${{ env.APK_FILE_DEBUG }}))
          echo "|Debug|$debug" >> $GITHUB_STEP_SUMMARY

      - name: Upload Artifacts Debug
        uses: actions/upload-artifact@v4
        with:
          name: FoldDevtools-debug-zh-${{ github.sha }}
          path: ${{ env.APK_FILE_DEBUG }}
